// ── Itinerary Data ──────────────────────────────────────────────
// Each stop has a `wiki` key used to fetch real images from Wikipedia REST API.

export const tripMeta = {
  title: 'Mangaluru → Wayanad',
  dates: 'May 28 – May 31',
  vehicle: 'Two-Wheeler / Motorcycle',
  startEnd: 'Mangaluru, Karnataka',
  totalDistance: '~675 km',
};

export const guidelines = [
  { icon: '🚫', title: 'Night Curfews', text: 'Forest checkposts (Tholpetty, Kutta, Muthanga) strictly ban vehicle movement between 9 PM and 6 AM. Cross all borders in daylight.' },
  { icon: '🐘', title: 'Wildlife Safaris', text: 'Two-wheelers are prohibited inside Muthanga and Tholpetty safari trails. Park at the forest office and take the official 4×4 Jeep safari.' },
  { icon: '📄', title: 'Border Crossings', text: 'You will cross state lines multiple times. Keep your RC, Insurance, and PUC easily accessible in a tank bag.' },
  { icon: '🌧️', title: 'Rain Gear', text: 'Late May sees pre-monsoon showers. Keep dry bags and raincoats at the top of your luggage.' },
];

export const days = [
  // ── DAY 1 ─────────────────────────────────────────────────────
  {
    day: 1,
    date: 'May 28',
    title: 'The Gonikoppa–Kabini Forest Loop',
    emoji: '🌄',
    distance: '~230 km',
    ridingTime: '~6 hrs',
    totalTime: '~14 hrs (riding + stops)',
    route: 'Mangaluru → Gonikoppa → Tholpetty → Kabini Backwaters → Nettara → Thirunelli',
    color: '#FF6B35',
    colorLight: 'rgba(255,107,53,0.15)',
    overnight: 'Thirunelli Temple',
    stops: [
      {
        name: 'Mangaluru',
        time: '05:30 AM',
        description: 'Leave Mangaluru at dawn. Carve up the Sampaje Ghat section, bypassing Madikeri for a heavy breakfast stop in Gonikoppa.',
        lat: 12.8714,
        lng: 74.8426,
        wiki: 'Mangalore',
        highlight: 'Start Point',
      },
      {
        name: 'Gonikoppa',
        time: '09:00 AM',
        description: 'Heavy breakfast stop in the heart of South Coorg. Famous for its plantation surroundings and local Kodava cuisine.',
        lat: 12.1539,
        lng: 75.9299,
        wiki: 'Gonikoppal',
        highlight: 'Breakfast Stop',
      },
      {
        name: 'Tholpetty Wildlife Sanctuary',
        time: '10:30 AM',
        description: 'Cross from Karnataka into Kerala at the Tholpetty checkpoint. This sanctuary is part of the Wayanad Wildlife Sanctuary and connects to the Nilgiri Biosphere.',
        lat: 11.9516,
        lng: 76.0599,
        wiki: 'Wayanad_Wildlife_Sanctuary',
        highlight: 'Border Crossing',
      },
      {
        name: 'Kabini Backwaters',
        time: '11:30 AM',
        description: 'Pivot east from Tholpetty towards Bavali to hit the Kabini Backwaters on the Karnataka side. Coast along the scenic reservoir fringes, take photos, and double back.',
        lat: 11.9800,
        lng: 76.2700,
        wiki: 'Kabini_River',
        highlight: 'Scenic Detour',
      },
      {
        name: 'Nettara Village',
        time: '02:30 PM',
        description: 'A quiet, agrarian border hamlet. Stretch your legs and grab a late local lunch amidst lush greenery.',
        lat: 11.8700,
        lng: 76.0700,
        wiki: 'Wayanad_district',
        highlight: 'Lunch Stop',
      },
      {
        name: 'Thirunelli Temple',
        time: '04:00 PM',
        description: 'Ride the slow, heavily forested dead-end mountain road up to the ancient Thirunelli Temple nestled under the Brahmagiri peaks. One of the most sacred Vishnu temples in Kerala.',
        lat: 11.9117,
        lng: 75.9958,
        wiki: 'Thirunelli_Temple',
        highlight: 'Day End / Overnight',
      },
    ],
  },
  // ── DAY 2 ─────────────────────────────────────────────────────
  {
    day: 2,
    date: 'May 29',
    title: 'River Islands & Interlock Trails',
    emoji: '🏝️',
    distance: '~40 km',
    ridingTime: '~1.5 hrs',
    totalTime: '~8 hrs (riding + exploration)',
    route: 'Thirunelli → Kuruva Dweep → Chekadi → Pulpally',
    color: '#00D4AA',
    colorLight: 'rgba(0,212,170,0.15)',
    overnight: 'Pulpally',
    stops: [
      {
        name: 'Thirunelli Temple (Start)',
        time: '07:30 AM',
        description: 'Begin the day starting from your overnight stay near the ancient Thirunelli Temple.',
        lat: 11.9117,
        lng: 75.9958,
        wiki: 'Thirunelli_Temple',
        highlight: 'Start Point',
      },
      {
        name: 'Kuruva Dweep',
        time: '08:30 AM',
        description: 'Park your bike at the checkpoint and take a bamboo raft to explore the densely wooded river islands on foot. A cluster of islands on the Kabini river with rich biodiversity.',
        lat: 11.8217,
        lng: 76.0922,
        wiki: 'Kuruva_Island',
        highlight: 'Must Visit',
      },
      {
        name: 'Chekadi Forest Village',
        time: '12:00 PM',
        description: 'The paved paths here slice straight through massive emerald paddy fields walled in by deep forest. A hidden gem of rural Wayanad.',
        lat: 11.8363,
        lng: 76.1127,
        wiki: 'Wayanad_district',
        highlight: 'Scenic Ride',
      },
      {
        name: 'Pulpally Interlock Road',
        time: '03:00 PM',
        description: 'Ride the famous Chakodi–Kappikunnu route. This unique public road is built from rustic brick pavers and winds tightly through cocoa and rubber plantations.',
        lat: 11.7963,
        lng: 76.1578,
        wiki: 'Pulpally',
        highlight: 'Day End / Overnight',
      },
    ],
  },
  // ── DAY 3 ─────────────────────────────────────────────────────
  {
    day: 3,
    date: 'May 30',
    title: 'Deep Woods & Massive Dams',
    emoji: '🌿',
    distance: '~110 km',
    ridingTime: '~3.5 hrs',
    totalTime: '~10 hrs (riding + safaris + hikes)',
    route: 'Pulpally → Vadakkanad → Muthanga → Edakkal Caves → Banasura Sagar Dam',
    color: '#A855F7',
    colorLight: 'rgba(168,85,247,0.15)',
    overnight: 'Banasura Sagar Dam',
    stops: [
      {
        name: 'Pulpally (Start)',
        time: '06:00 AM',
        description: 'Start your ride early from Pulpally to catch the morning mist and wildlife activity.',
        lat: 11.7963,
        lng: 76.1578,
        wiki: 'Pulpally',
        highlight: 'Start Point',
      },
      {
        name: 'Vadakkanad',
        time: '06:30 AM',
        description: 'Early morning ride parallel to the forest boundary fence — a prime spot for morning wild elephant sightings in the misty dawn.',
        lat: 11.7000,
        lng: 76.2900,
        wiki: 'Wayanad_Wildlife_Sanctuary',
        highlight: 'Wildlife',
      },
      {
        name: 'Muthanga Wildlife Sanctuary',
        time: '08:00 AM',
        description: 'Secure your bike at the forest office and hop into an official 4×4 Jeep for the deep jungle safari. Home to tigers, elephants, and rich birdlife.',
        lat: 11.6700,
        lng: 76.3600,
        wiki: 'Muthanga_Wildlife_Sanctuary',
        highlight: 'Jeep Safari',
      },
      {
        name: 'Edakkal Caves',
        time: '12:00 PM',
        description: 'Navigate the steep concrete ascent, park your bike, and hike up the rock steps to view prehistoric Neolithic carvings dating back to 6000 BCE.',
        lat: 11.6267,
        lng: 76.2343,
        wiki: 'Edakkal_Caves',
        highlight: 'Historic',
      },
      {
        name: 'Banasura Sagar Dam',
        time: '03:30 PM',
        description: 'Walk along the massive earthen embankment of India\'s largest earth dam. The surrounding Banasura hills and reservoir create a breathtaking panorama.',
        lat: 11.6700,
        lng: 75.9578,
        wiki: 'Banasura_Sagar_Dam',
        highlight: 'Day End / Overnight',
      },
    ],
  },
  // ── DAY 4 ─────────────────────────────────────────────────────
  {
    day: 4,
    date: 'May 31',
    title: 'Tribal Peaks & The Palchuram Drop',
    emoji: '⛰️',
    distance: '~295 km',
    ridingTime: '~7.5 hrs',
    totalTime: '~13 hrs (riding + stops)',
    route: 'Banasura Sagar → En Ooru → Palchuram View Point → Kannur → Mangaluru',
    color: '#F43F5E',
    colorLight: 'rgba(244,63,94,0.15)',
    overnight: 'Home! 🏠',
    stops: [
      {
        name: 'Banasura Sagar Dam (Start)',
        time: '06:30 AM',
        description: 'Leave the Banasura area and head south towards Vythiri/Lakkidi for the final day\'s journey.',
        lat: 11.6700,
        lng: 75.9578,
        wiki: 'Banasura_Sagar_Dam',
        highlight: 'Start Point',
      },
      {
        name: 'En Ooru Tribal Village',
        time: '07:30 AM',
        description: 'Visit this stunning tribal heritage village terraced into the mountainside near Lakkidi. Park at the bottom and take the official shuttle jeep up the extreme incline.',
        lat: 11.5400,
        lng: 76.0200,
        wiki: 'Lakkidi,_Wayanad',
        highlight: 'Heritage',
      },
      {
        name: 'Palchuram View Point',
        time: '11:00 AM',
        description: 'Stop for a panoramic valley shot, then navigate the sharp hairpins down the mountain. Steeper and less crowded than Thamarassery — a brilliant rider\'s road.',
        lat: 11.8560,
        lng: 75.9000,
        wiki: 'Paithalmala',
        highlight: 'Scenic View',
      },
      {
        name: 'Kannur',
        time: '01:30 PM',
        description: 'Level out into the plains and cut west to the coast at Kannur. Stop for a heavy Malabar lunch and rest by the beach. Visit St. Angelo Fort if time permits.',
        lat: 11.8745,
        lng: 75.3704,
        wiki: 'Kannur',
        highlight: 'Lunch & Coast',
      },
      {
        name: 'Mangaluru (Arrival)',
        time: '08:30 PM',
        description: 'Merge onto the NH-66 highway and open up the throttle for a smooth, straight evening run back up the coastline. Trip complete! 🎉',
        lat: 12.8714,
        lng: 74.8426,
        wiki: 'Mangalore',
        highlight: 'Finish 🏁',
      },
    ],
  },
];
