// ── Itinerary Data ──────────────────────────────────────────────
// Each stop has a `wiki` key used to fetch real images from Wikipedia REST API.

export const tripMeta = {
  title: 'Mangaluru → Wayanad',
  dates: 'May 28 – May 31',
  vehicle: 'Two-Wheeler / Motorcycle',
  startEnd: 'Mangaluru, Karnataka',
  totalDistance: '~675 km',
};

export const guidelines = [
  { icon: '🚫', title: 'Night Curfews', text: 'Forest checkposts (Tholpetty, Kutta, Muthanga) strictly ban vehicle movement between 9 PM and 6 AM. Cross all borders in daylight.' },
  { icon: '🐘', title: 'Wildlife Safaris', text: 'Two-wheelers are prohibited inside Muthanga and Tholpetty safari trails. Park at the forest office and take the official 4×4 Jeep safari.' },
  { icon: '📄', title: 'Border Crossings', text: 'You will cross state lines multiple times. Keep your RC, Insurance, and PUC easily accessible in a tank bag.' },
  { icon: '🌧️', title: 'Rain Gear', text: 'Late May sees pre-monsoon showers. Keep dry bags and raincoats at the top of your luggage.' },
];

export const days = [
  // ── DAY 1 ─────────────────────────────────────────────────────
  {
    day: 1,
    date: 'May 28',
    title: 'The Gonikoppa–Iruppu Forest Loop',
    emoji: '🌄',
    distance: '~230 km',
    ridingTime: '~6 hrs',
    totalTime: '~14 hrs (riding + stops)',
    route: 'Mangaluru → Gonikoppa → Iruppu Waterfalls → Thirunelli Route → Appapara → Nettara Village → Mananthavady',
    color: '#FF6B35',
    colorLight: 'rgba(255,107,53,0.15)',
    overnight: 'Mananthavady Hotel Riviera',
    stops: [
      {
        name: 'Mangaluru',
        time: '05:30 AM',
        description: 'Leave Mangaluru at dawn. Carve up the Sampaje Ghat section, bypassing Madikeri for a heavy breakfast stop in Gonikoppa.',
        lat: 12.8714,
        lng: 74.8426,
        wiki: 'Mangalore',
        highlight: 'Start Point',
      },
      {
        name: 'Gonikoppa',
        time: '09:00 AM',
        description: 'Heavy breakfast stop in the heart of South Coorg. Famous for its plantation surroundings and local Kodava cuisine.',
        lat: 12.1539,
        lng: 75.9299,
        wiki: 'Gonikoppal',
        highlight: 'Breakfast Stop',
      },
      {
        name: 'Iruppu Waterfalls',
        time: '11:00 AM',
        description: 'A picturesque waterfall cascading down the Brahmagiri hills. A short hike from the parking area takes you to the falls.',
        lat: 11.9661,
        lng: 75.9833,
        wiki: 'Irupu_Falls',
        highlight: 'Must Visit',
      },
      {
        name: 'Thirunelli Route & Appapara',
        time: '03:30 PM',
        description: 'Take the scenic forest route towards Thirunelli and pass through Appapara. The dense forest canopy and winding roads make for an incredible ride.',
        lat: 11.9117,
        lng: 75.9958,
        wiki: 'Thirunelli',
        highlight: 'Scenic Ride',
      },
      {
        name: 'Nettara Village',
        time: '05:30 PM',
        description: 'Stop by Nettara village to catch a beautiful evening sunset over the lush greenery and agrarian landscapes.',
        lat: 11.8700,
        lng: 76.0700,
        wiki: 'Wayanad_district',
        highlight: 'Sunset',
      },
      {
        name: 'Mananthavady Hotel Riviera',
        time: '07:00 PM',
        description: 'Arrive at your base camp for the next 3 nights. Check in, unpack, and relax by the Mananthavady riverside.',
        lat: 11.8016,
        lng: 76.0028,
        wiki: 'Mananthavady',
        highlight: 'Day End / Overnight',
      },
    ],
  },
  // ── DAY 2 ─────────────────────────────────────────────────────
  {
    day: 2,
    date: 'May 29',
    title: 'River Islands & Interlock Trails',
    emoji: '🏝️',
    distance: '~120 km',
    ridingTime: '~4 hrs',
    totalTime: '~11 hrs (riding + exploration)',
    route: 'Mananthavady → Kuruvadweep → Chekadi → Pulpally → Banasura Sagar Dam → Koodalkadavu → Mananthavady',
    color: '#00D4AA',
    colorLight: 'rgba(0,212,170,0.15)',
    overnight: 'Mananthavady Hotel Riviera',
    stops: [
      {
        name: 'Mananthavady Hotel Riviera (Start)',
        time: '07:30 AM',
        description: 'Begin the day starting from your basecamp in Mananthavady.',
        lat: 11.8016,
        lng: 76.0028,
        wiki: 'Mananthavady',
        highlight: 'Start Point',
      },
      {
        name: 'Kuruvadweep',
        time: '09:00 AM',
        description: 'Park your bike at the checkpoint and take a bamboo raft to explore the densely wooded river islands on foot. Enjoy a full 2 hours here.',
        lat: 11.8217,
        lng: 76.0922,
        wiki: 'Kuruva_Island',
        highlight: 'Must Visit',
      },
      {
        name: 'Chekadi & Pulpally Interlock Road',
        time: '11:30 AM',
        description: 'Ride the famous Kappikunnu–Pulpally route through Chekadi. This unique public road is built from rustic brick pavers.',
        lat: 11.7963,
        lng: 76.1578,
        wiki: 'Pulpally',
        highlight: 'Scenic Ride',
      },
      {
        name: 'Kottamurattu View point',
        time: '12:00 PM',
        description: 'Stop at Kottamurattu View point in Veliyambam for sweeping views of the surrounding hills.',
        lat: 11.7802,
        lng: 76.1424,
        wiki: 'Wayanad_district',
        highlight: 'View Point',
      },
      {
        name: 'Lunch Break (Panamaram)',
        time: '01:00 PM',
        description: 'Grab a local lunch on your way heading west toward the dam.',
        lat: 11.7275,
        lng: 76.0722,
        wiki: 'Panamaram',
        highlight: 'Lunch Stop',
      },
      {
        name: 'Banasura Sagar Dam',
        time: '02:30 PM',
        description: 'Walk along the massive earthen embankment of India\'s largest earth dam.',
        lat: 11.6700,
        lng: 75.9578,
        wiki: 'Banasura_Sagar_Dam',
        highlight: 'Must Visit',
      },
      {
        name: 'Koodalkadavu Check Dam',
        time: '04:00 PM',
        description: 'Arrive early at this peaceful check dam. Spend plenty of time bathing, swimming, and enjoying the water until sunset.',
        lat: 11.8044,
        lng: 76.0763,
        wiki: 'Wayanad_district',
        highlight: 'Bathing & Enjoyment',
      },
      {
        name: 'Mananthavady Hotel Riviera',
        time: '06:30 PM',
        description: 'Return to your basecamp after a long day in the water. Enjoy dinner in the local town.',
        lat: 11.8016,
        lng: 76.0028,
        wiki: 'Mananthavady',
        highlight: 'Day End / Overnight',
      },
    ],
  },
  // ── DAY 3 ─────────────────────────────────────────────────────
  {
    day: 3,
    date: 'May 30',
    title: 'Sunrise Treks & Safari Adventures',
    emoji: '🐅',
    distance: '~150 km',
    ridingTime: '~4.5 hrs',
    totalTime: '~14 hrs (riding + treks + safaris)',
    route: 'Mananthavady → Cheengeri → Nellarachal → Edakkal Caves → Vadakkanad → Muthanga → Mananthavady',
    color: '#A855F7',
    colorLight: 'rgba(168,85,247,0.15)',
    overnight: 'Mananthavady Hotel Riviera',
    stops: [
      {
        name: 'Mananthavady Hotel Riviera (Start)',
        time: '04:00 AM',
        description: 'Start your ride extremely early to reach the base of Cheengeri Mala before sunrise.',
        lat: 11.8016,
        lng: 76.0028,
        wiki: 'Mananthavady',
        highlight: 'Start Point',
      },
      {
        name: 'Cheengeri Mala Trekking',
        time: '05:00 AM',
        description: 'Arrive at 5:00 AM sharp to begin your sunrise trek. An incredible hike offering panoramic views of the Karapuzha Reservoir and surrounding mist-covered peaks.',
        lat: 11.6181,
        lng: 76.1985,
        wiki: 'Wayanad_district',
        highlight: 'Sunrise Trek',
      },
      {
        name: 'Breakfast (Ambalavayal)',
        time: '08:30 AM',
        description: 'After descending from the trek, stop in the nearby town for a hearty breakfast and fresh filter coffee.',
        lat: 11.6212,
        lng: 76.2132,
        wiki: 'Ambalavayal',
        highlight: 'Breakfast Stop',
      },
      {
        name: 'Nellarachal',
        time: '09:30 AM',
        description: 'Head to Nellarachal for a scenic waterfront break by the backwaters.',
        lat: 11.6013,
        lng: 76.1770,
        wiki: 'Karapuzha_Dam',
        highlight: 'Scenic View',
      },
      {
        name: 'Edakkal Caves',
        time: '11:00 AM',
        description: 'Navigate the steep concrete ascent and hike up the rock steps to view prehistoric Neolithic carvings.',
        lat: 11.6268,
        lng: 76.2343,
        wiki: 'Edakkal_Caves',
        highlight: 'Historic',
      },
      {
        name: 'Lunch (Sultan Bathery)',
        time: '12:30 PM',
        description: 'Grab a solid lunch in Sultan Bathery on your way towards Muthanga.',
        lat: 11.6664,
        lng: 76.2625,
        wiki: 'Sulthan_Bathery',
        highlight: 'Lunch Stop',
      },
      {
        name: 'Vadakkanad',
        time: '01:45 PM',
        description: 'Ride through Vadakkanad towards the forest boundaries. A beautiful transit route heading towards Muthanga.',
        lat: 11.7284,
        lng: 76.2740,
        wiki: 'Wayanad_Wildlife_Sanctuary',
        highlight: 'Transit',
      },
      {
        name: 'Muthanga Safari',
        time: '02:30 PM',
        description: 'Arrive at the ticket counter for the afternoon Jeep safari. The safari takes about 2 hours, exiting around 04:30 PM.',
        lat: 11.6719,
        lng: 76.3689,
        wiki: 'Muthanga_Wildlife_Sanctuary',
        highlight: 'Jeep Safari',
      },
      {
        name: 'Tea Break (Post-Safari)',
        time: '04:30 PM',
        description: 'Right after exiting the safari, grab some hot tea and snacks near the forest gate before the long ride back west.',
        lat: 11.6719,
        lng: 76.3689,
        wiki: 'Muthanga_Wildlife_Sanctuary',
        highlight: 'Tea Break',
      },
      {
        name: 'Mananthavady Hotel Riviera',
        time: '06:30 PM',
        description: 'Return to basecamp for your final night in Wayanad. Grab dinner and rest up!',
        lat: 11.8016,
        lng: 76.0028,
        wiki: 'Mananthavady',
        highlight: 'Day End / Overnight',
      },
    ],
  },
  // ── DAY 4 ─────────────────────────────────────────────────────
  {
    day: 4,
    date: 'May 31',
    title: 'Tribal Peaks & The Palchuram Drop',
    emoji: '⛰️',
    distance: '~295 km',
    ridingTime: '~7.5 hrs',
    totalTime: '~13 hrs (riding + stops)',
    route: 'Mananthavady → Palchuram View Point → Kottiyoor → Kannur → Mangaluru',
    color: '#F43F5E',
    colorLight: 'rgba(244,63,94,0.15)',
    overnight: 'Home! 🏠',
    stops: [
      {
        name: 'Mananthavady Hotel Riviera (Start)',
        time: '08:00 AM',
        description: 'Check out from your basecamp, pack your bags, and prepare for the final ride down the ghats.',
        lat: 11.8016,
        lng: 76.0028,
        wiki: 'Mananthavady',
        highlight: 'Start Point',
      },
      {
        name: 'Palchuram View Point',
        time: '09:30 AM',
        description: 'Stop for a panoramic valley shot, then navigate the sharp hairpins down the mountain. Steeper and less crowded than Thamarassery — a brilliant rider\'s road.',
        lat: 11.8523,
        lng: 75.9099,
        wiki: 'Paithalmala',
        highlight: 'Scenic View',
      },
      {
        name: 'Kottiyoor',
        time: '10:30 AM',
        description: 'After descending the ghats, take a quick break in the lush green town of Kottiyoor before hitting the highways.',
        lat: 11.8845,
        lng: 75.8883,
        wiki: 'Kottiyoor',
        highlight: 'Transit',
      },
      {
        name: 'Kannur',
        time: '01:30 PM',
        description: 'Level out into the plains and cut west to the coast at Kannur. Stop for a heavy Malabar lunch and rest by the beach. Visit St. Angelo Fort if time permits.',
        lat: 11.8705,
        lng: 75.3679,
        wiki: 'Kannur',
        highlight: 'Lunch & Coast',
      },
      {
        name: 'Mangaluru (Arrival)',
        time: '08:30 PM',
        description: 'Merge onto the NH-66 highway and open up the throttle for a smooth, straight evening run back up the coastline. Trip complete! 🎉',
        lat: 12.8855,
        lng: 74.8388,
        wiki: 'Mangalore',
        highlight: 'Finish 🏁',
      },
    ],
  },
];
